services:
  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit:latest
    container_name: fluent-bit
    ports:
      - "514:514/udp"    # Firewall logs
      - "515:515/udp"    # Network logs
      - "7070:7070"      # HTTP API /ingest
      - "9880:9880"      # CrowdStrike sample
    volumes:
      - ./fluent-bit-config:/fluent-bit/config
      - ./logs:/logs
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/config/fluent-bit.conf

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: my-app
    ports:
      - "3000:3000"      # FastAPI app
    volumes:
      - ./app:/app
      - ./logs:/logs
    command: uvicorn main:app --reload --host 0.0.0.0 --port 3000
